### ISSUE TITLE
Is a 3D model of the board available?

### ISSUE THREAD

**Issue by Pinchie** [srg74/Controller-for-WLED-firmware#2]
I've got five on the way from PCBWay (although the components themselves will take far longer than the boards). In the meantime I'd like to see about getting a case designed to fit the board.

Would you have a model of the board that I can import in order to look at doing that? I do most of my work in Fusion 360, but I do have Solidworks for changing between formats as well so any format should do.

Thanks again for the project,
Mark

**Comment by srg74** [comment]
I never did a 3D models but worth to try it. https://github.com/srg74/Controller-for-WLED-firmware/tree/master/resources

**Comment by Pinchie** [comment]
That f3d file looks perfect, thank you 👍
