### ISSUE TITLE
Help getting started 

### ISSUE THREAD

**Issue by diabolic812** [srg74/Controller-for-WLED-firmware#3]
Hi. I'm a novice and would love some more information on how to assemble everything.  A wiki similar to the WLED Wemos board shield wiki would be great. I ordered the PCB as will as all of the parts you've linked. But I don't see a complete list of everything I need to order. Please help! 
Thanks

**Comment by srg74** [comment]
BOM file is in "resources" folder. Regarding wiki I don't have a chance to create one.
