### ISSUE TITLE
Gerber Files

### ISSUE THREAD

**Issue by FireBall1725** [srg74/Controller-for-WLED-firmware#4]
Hello,

Would it be possible to get the gerber files?

Thanks!

**Comment by srg74** [comment]
You can order PCB from PCBway.com for a low cost all gerbers there. Follow link https://www.pcbway.com/project/shareproject/Controller_for_WLED_firmware_in_waterproof_enclosure.html

**Comment by FireBall1725** [comment]
Yes, I have ordered some from PCBway already, however I wanted to change a few things with your design, and the unique shaped pcb has been difficult for me to replicate, so I was hoping I would be able to get the gerber files to make that process easier.

I noticed the project is marked open source, but i couldn't find the source files anywhere and on PCBway is says the author denied access to the gerber files.

Is this not an open source (MIT) licensed project?

**Comment by srg74** [comment]
Added https://github.com/srg74/Controller-for-WLED-firmware/blob/master/resources/Gerbers.zip

**Comment by FireBall1725** [comment]
Thank you so much! This is as far as I got after a few weeks 
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/727458/104109219-c3992680-5299-11eb-8e75-fc898283e751.png"> I was having so many issues with figuring out the radius of the curves.
