### ISSUE TITLE
Not an issue, seeking clarification

### ISSUE THREAD

**Issue by chicknlil** [srg74/Controller-for-WLED-firmware#5]
Your controller seems to be exactly what I'm looking for (outdoor safe + antenna).  But based on the links provided, I can't tell if buying from the [first PCBWay link](https://www.pcbway.com/project/shareproject/Controller_for_WLED_firmware_in_waterproof_enclosure.html) supplies all the necessary pieces, or if I need to be buying additional items elsewhere.

Thanks for your time, and for making such a useful device!

**Comment by srg74** [comment]
It's clearly stated that only a PCB can be purchased from PCBWay. BOM file is located here https://github.com/srg74/Controller-for-WLED-firmware/tree/master/resources

**Comment by chicknlil** [comment]
I wasn't asking about files. 

I was referring to the materials which make up the controller - is that link that I included in my initial post (which is also part of your readme) all inclusive, or do I need to purchase additional items to assemble the controller? I am happy to support you by buying from sites that generate you affiliate income, I just need to know if that is necessary above and beyond that link.

Thank you.

**Comment by srg74** [comment]
All parts is electronic parts is listed in BOM. Some items is listed under https://github.com/srg74/Controller-for-WLED-firmware#materials-used. Read carefully and you will find everything what is require to assemble this project.

**Comment by chicknlil** [comment]
I have read carefully; the information is not in any way clear, thus why I posted seeking clarification which you seem unwilling to provide.

It's fine, I won't bother you any further and I'll figure it out on my own.

**Comment by srg74** [comment]
I don't mind to help. Better if you ask something in particular. If you want more details better to visit WLED Discord https://discord.gg/KuqP7NE my name there is Serg74#5959
